# -------------------------------------
# REQUIRED METADATA (MUST BE AT THE TOP)
# -------------------------------------
name: grit
description: "A sleek, dark-themed fitness tracking app built with Flutter."
publish_to: 'none'
version: 1.0.0+1
# -------------------------------------

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI/Aesthetic
  flutter_feather_icons: ^2.0.0 
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # Modular/Pro-Level Packages (Forced updates applied)
  go_router: ^16.2.4
  get_it: ^8.2.0
  injectable: ^2.5.2
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation Tools
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1

# -------------------------------------
flutter:
  uses-material-design: true