import 'package:flutter/foundation.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
// Note: 'di.config.dart' is the file generated by build_runner
// You must run the command `flutter pub run build_runner build --delete-conflicting-outputs`

final getIt = GetIt.instance;

@InjectableInit(  
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
Future<void> configureDependencies() async {
  // This function body will be replaced by the generated call: getIt.init();
  if (kDebugMode) {
    debugPrint('--- DI Configuration Placeholder Executed. Run build_runner! ---');
  }
}