import 'package:flutter/material.dart';
import 'app/app.dart';
import 'core/di.dart';
import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // Will be generated by flutterfire configure

void main() async {
  // Binds Flutter widgets engine to the platform, needed for async calls like Firebase
  WidgetsFlutterBinding.ensureInitialized();
  
  // 1. Initialize Firebase (CRITICAL STEP for database)
  // NOTE: Uncomment the line below after running 'flutterfire configure'
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform,);
  await Firebase.initializeApp();

  // 2. Initialize Dependency Injection
  await configureDependencies();

  // 3. Run the application
  runApp(const GritApp());
}
